# Generated by Django 4.2.11 on 2024-06-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bitgo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="address_id",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
