# Generated by Django 4.2.11 on 2024-06-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bitgo", "0002_address_address_id_alter_address_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="label",
            field=models.CharField(default="test label", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="_is_active",
            field=models.BooleanField(default=True),
        ),
    ]
