# Generated by Django 4.2.11 on 2024-06-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app_root", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyfilesdetails",
            name="logo_file",
            field=models.FileField(
                max_length=1000, upload_to="home/kc/blancexchangeapi/media/images"
            ),
        ),
    ]
