# Generated by Django 4.2.11 on 2024-06-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_deposit_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_pix",
            field=models.ImageField(default=None, upload_to=""),
            preserve_default=False,
        ),
    ]
