# Generated by Django 4.2.11 on 2024-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_profile_profile_pix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pix",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
