# Generated by Django 4.2.11 on 2024-07-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app_root_security_auth", "0002_alter_codegenerator_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessagePromptModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_body", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
