# Generated by Django 4.2.11 on 2024-08-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_auth', '0003_messagepromptmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='codegenerator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
