# Generated by Django 4.2.11 on 2024-06-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app_root_security_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
