# Generated by Django 4.2.11 on 2024-06-20 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_app_root_security_user", "0002_user_is_confirmed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_confirmed",
        ),
    ]
